### ISSUE TITLE
It is not a good idea to create a function for loading exactly two files.

### ISSUE THREAD

**Issue by SergSlipushenko** [Iaroslavrul/Poligon_finder#4]
https://github.com/Iaroslavrul/Poligon_finder/blob/ad99798590ff7bb0d9c7ba1ce61d82c87b4e243a/geo_test.py#L19

Fix naming or just inline this code

**Comment by Iaroslavrul** [comment]
Sergey, do you mean that reading a file should be done directly in the function main or that the function should take a variable number of arguments (*args)?
Thanks

**Comment by Iaroslavrul** [comment]
I close this issue since it was resolved.
Thank you!
