### ISSUE TITLE
please use RTree index here

### ISSUE THREAD

**Issue by SergSlipushenko** [Iaroslavrul/Poligon_finder#5]
https://github.com/Iaroslavrul/Poligon_finder/blob/ad99798590ff7bb0d9c7ba1ce61d82c87b4e243a/geo_test.py#L112

https://automating-gis-processes.github.io/site/notebooks/L3/spatial_index.html

**Comment by Iaroslavrul** [comment]
You are right, it really improves the performance.
I close this issue since it was resolved.
Thank you!
